name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
    - "*"

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@3c0a6ca5c66e31614579048b57259114fb69ac28
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: csp-report-lite
        
  build-and-publish-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and publish tagged Docker image
      uses: VaultVulp/gp-docker-action@3c0a6ca5c66e31614579048b57259114fb69ac28
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: csp-report-lite
        extract-git-tag: true 
